### PR TITLE
Update Chat-Copilot to SemanticKernel Beta 7

### PR DESCRIPTION
**Pull request by crickman**
### Motivation and Context

Stay in sync with the "latest and greatest"!

**VERIFIED**

### Description

https://github.com/microsoft/semantic-kernel/pkgs/nuget/Microsoft.SemanticKernel.Core/148204203

image
image

### Contribution Checklist

- [X] The code builds clean without any errors or warnings
- [X] The PR follows the [Contribution Guidelines](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [X] All unit tests pass, and I have added new tests where possible
- [X] I didn't break anyone :smile:

### CODE REVIEW

**Comment by crickman** [comment]
Waiting for kernel-memory nuget update (currently this PR is draft)

**Review by glahaye — DISMISSED** [review]

**Comment by crickman** [comment]
Some OpenAI links shifted...the "Models" one may be problematic.

**Review by glahaye — DISMISSED** [review]

**Comment by momuno** [comment]
@crickman I'm seeing the same issues with platform.openai.com markdown link check.  the 3 links getting 403 are valid.

**Review by glahaye — APPROVED** [review]

**Review by momuno — CHANGES_REQUESTED** [review]
I believe this was tested for plugin functionality in CC and does not work.  Let's get that issue figured out and then we can merge this :)

**Comment by momuno** [comment]
Replaced with #615

**Comment by glahaye** [comment]
You mean #626

**Comment by momuno** [comment]
> You mean #626

yes! this is what happens when you work while being sick lol

**Pull request closed without merging**
